<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>B3.Trading.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B3.Trading.Domain\B3.Trading.Domain.csproj" />
    <ProjectReference Include="..\B3.Trading.Application\B3.Trading.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="B3.EntryPoint.Client" Version="0.14.1" />
    <PackageReference Include="System.IO.Hashing" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="B3.Trading.Api" />
    <InternalsVisibleTo Include="B3.Trading.Host" />
    <InternalsVisibleTo Include="B3.Trading.Application.Tests" />
  </ItemGroup>

</Project>
