<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="B3.EntryPoint.Client.TestPeer" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="FsCheck.Xunit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xRetry" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\B3.Trading.Application\B3.Trading.Application.csproj" />
    <ProjectReference Include="..\..\src\B3.Trading.Infrastructure\B3.Trading.Infrastructure.csproj" />
    <ProjectReference Include="..\..\tools\B3.Trading.IdentityMaintenance\B3.Trading.IdentityMaintenance.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
