<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>B3.Trading.EntryPointListener</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\B3.Trading.Application\B3.Trading.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="B3.EntryPoint.Sbe" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="B3.Trading.EntryPointListener.Tests" />
  </ItemGroup>

</Project>
