<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>B3.Trading.Host</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B3.Trading.Domain\B3.Trading.Domain.csproj" />
    <ProjectReference Include="..\B3.Trading.Application\B3.Trading.Application.csproj" />
    <ProjectReference Include="..\B3.Trading.Infrastructure\B3.Trading.Infrastructure.csproj" />
    <ProjectReference Include="..\B3.Trading.Api\B3.Trading.Api.csproj" />
    <ProjectReference Include="..\B3.Trading.EntryPointListener\B3.Trading.EntryPointListener.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="B3.MarketData.WebSocketClient" />
  </ItemGroup>

</Project>
